begin;

create extension if not exists pgtap with schema extensions;

select extensions.plan(10);

create table public.future_default_privileges_table_probe (
  id bigint generated by default as identity primary key
);

create sequence public.future_default_privileges_sequence_probe;

create function public.future_default_privileges_function_probe()
returns integer
language sql
set search_path = ''
as $$select 1$$;

select extensions.ok(
  not (
    has_table_privilege('anon', 'public.future_default_privileges_table_probe', 'select')
    or has_table_privilege('anon', 'public.future_default_privileges_table_probe', 'insert')
    or has_table_privilege('anon', 'public.future_default_privileges_table_probe', 'update')
    or has_table_privilege('anon', 'public.future_default_privileges_table_probe', 'delete')
  ),
  'Future postgres-owned public tables grant no CRUD privilege to anon'
);

select extensions.ok(
  not (
    has_table_privilege('authenticated', 'public.future_default_privileges_table_probe', 'select')
    or has_table_privilege('authenticated', 'public.future_default_privileges_table_probe', 'insert')
    or has_table_privilege('authenticated', 'public.future_default_privileges_table_probe', 'update')
    or has_table_privilege('authenticated', 'public.future_default_privileges_table_probe', 'delete')
  ),
  'Future postgres-owned public tables grant no CRUD privilege to authenticated'
);

select extensions.ok(
  not (
    has_table_privilege('service_role', 'public.future_default_privileges_table_probe', 'select')
    or has_table_privilege('service_role', 'public.future_default_privileges_table_probe', 'insert')
    or has_table_privilege('service_role', 'public.future_default_privileges_table_probe', 'update')
    or has_table_privilege('service_role', 'public.future_default_privileges_table_probe', 'delete')
  ),
  'Future postgres-owned public tables grant no CRUD privilege to service_role'
);

select extensions.ok(
  not (
    has_sequence_privilege('anon', 'public.future_default_privileges_sequence_probe', 'usage')
    or has_sequence_privilege('anon', 'public.future_default_privileges_sequence_probe', 'select')
  ),
  'Future postgres-owned public sequences grant no use privilege to anon'
);

select extensions.ok(
  not (
    has_sequence_privilege('authenticated', 'public.future_default_privileges_sequence_probe', 'usage')
    or has_sequence_privilege('authenticated', 'public.future_default_privileges_sequence_probe', 'select')
  ),
  'Future postgres-owned public sequences grant no use privilege to authenticated'
);

select extensions.ok(
  not (
    has_sequence_privilege('service_role', 'public.future_default_privileges_sequence_probe', 'usage')
    or has_sequence_privilege('service_role', 'public.future_default_privileges_sequence_probe', 'select')
  ),
  'Future postgres-owned public sequences grant no use privilege to service_role'
);

select extensions.ok(
  not has_function_privilege('anon', 'public.future_default_privileges_function_probe()', 'execute'),
  'Future postgres-owned public functions grant no execute privilege to anon'
);

select extensions.ok(
  not has_function_privilege('authenticated', 'public.future_default_privileges_function_probe()', 'execute'),
  'Future postgres-owned public functions grant no execute privilege to authenticated'
);

select extensions.ok(
  not has_function_privilege('service_role', 'public.future_default_privileges_function_probe()', 'execute'),
  'Future postgres-owned public functions grant no execute privilege to service_role'
);

select extensions.ok(
  not exists (
    select 1
    from pg_catalog.pg_proc as procedure
    cross join lateral pg_catalog.aclexplode(
      coalesce(
        procedure.proacl,
        pg_catalog.acldefault('f', procedure.proowner)
      )
    ) as privilege
    where procedure.oid = 'public.future_default_privileges_function_probe()'::regprocedure
      and privilege.grantee = 0
      and privilege.privilege_type = 'EXECUTE'
  ),
  'Future postgres-owned functions have no PUBLIC execute privilege'
);

select * from extensions.finish();
rollback;
